name: Bundle Install

on:
  push:
    paths:
      - 'Gemfile'
      - '.github/workflows/bundle_install.yml'

jobs:
  bundle_install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.2' # Use the version of Ruby that your project requires

    - name: Install dependencies
      run: bundle install

    - name: Commit Gemfile.lock
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Gemfile.lock
        git commit -m "Update Gemfile.lock" -a || echo "No changes to commit"
        git push
